// ─────────────────────────────────────────────────────────────
// CLI argument parsing with clap derive macros
// ─────────────────────────────────────────────────────────────
//
// clap is the standard Rust crate for building CLIs.  With the
// `derive` feature, `#[derive(Parser)]` and `#[derive(Subcommand)]`
// generate all the parsing code at compile time — we just declare
// the structure and clap handles validation, help formatting, and
// error messages automatically.
//
// Derive macros are NOT functions — they inject code at compile
// time by generating trait implementations based on the struct
// fields, types, and attributes we provide.

use clap::{Parser, Subcommand};

/// Root CLI structure.  Every field declared here becomes either
/// a global flag/option or a subcommand dispatcher.
///
/// `#[derive(Parser)]` gives this struct the method `Cli::parse()`,
/// which reads `std::env::args()` automatically.
///
/// `#[command(...)]` configures the binary metadata shown in --help:
///   name    → program name (defaults to the crate name)
///   version → reads version from Cargo.toml at compile time
///   about   → short description
#[derive(Parser)]
#[command(name = "rsfactai", version, about = "Codebase analysis engine")]
pub struct Cli {
    /// The subcommand chosen by the user.
    /// `#[command(subcommand)]` tells clap that the next positional
    /// argument must match one of the `Command` enum variants.
    /// Wrapping in `Option` makes subcommands optional, allowing
    /// global flags like `--license` to work without one.
    #[command(subcommand)]
    pub command: Option<Command>,

    /// Global flag: print license information and exit.
    /// `short = 'L'` makes `-L` an alias for `--license`.
    #[arg(short = 'L', long, help = "Print license information")]
    pub license: bool,
}

/// Available subcommands.  Each variant becomes a CLI subcommand
/// with its name derived in kebab-case (Analyse → "analyse",
/// Version → "version").
///
/// The `///` doc comment above each variant is shown as the
/// subcommand description in --help.
#[derive(Subcommand)]
pub enum Command {
    /// Analyze a file or directory and print a project summary.
    Analyse {
        /// Path to the file or directory to analyze.
        /// `#[arg(help = "...")]` provides the help text shown
        /// for this positional argument in --help.
        #[arg(help = "Path to the file or directory to analyze")]
        path: String,
    },
    /// Show version information.
    Version,
}

/// Entry point for CLI parsing.  A thin wrapper around
/// `Cli::parse()` generated by the derive macro.  It reads
/// `env::args()`, validates, and returns a `Cli` value.
/// Invalid input, `--help`, and `--version` are handled
/// internally by clap (it prints the message and exits).
pub fn parse_args() -> Cli {
    Cli::parse()
}
