// CLI argument parsing with `clap`
// `clap` is the standard Rust crate for building CLIs.
// With the `derive` feature, macros like `#[derive(Parser)]`
// and `#[derive(Subcommand)]` generate all the parsing code
// at compile time. You just declare the structure, and clap
// handles validation, help formatting, error messages, etc.
//
// Derive macros (`#[derive(...)]`) are NOT regular functions.
// They inject code during compilation — the compiler expands
// the macro and generates trait implementations (like `Parser`
// and `Subcommand`) based on your struct fields, types, and
// attributes.

use clap::{Parser, Subcommand};

// Root CLI struct
// `#[derive(Parser)]` gives this struct the method `Cli::parse()`,
// which reads `std::env::args()` automatically and fills the
// fields with the parsed values.
//
// `#[command(...)]` configures the binary metadata:
//   name    → program name (defaults to the crate name)
//   version → reads `version` from Cargo.toml automatically
//             (expands to `env!("CARGO_PKG_VERSION")` at compile time)
//   about   → short description shown in `--help`
#[derive(Parser)]
#[command(name = "rsfactai", version, about = "Codebase analysis engine")]
pub struct Cli {
    // `command` holds the subcommand chosen by the user.
    // `#[command(subcommand)]` tells clap: "the next argument
    // must be one of the Command enum variants".
    // Each variant becomes a subcommand (e.g. "analyse", "version").
    #[command(subcommand)]
    pub command: Command,
}

// Subcommand enum
// `#[derive(Subcommand)]` turns each enum variant into a CLI
// subcommand. The subcommand name is derived from the variant
// name in kebab-case:
//   Analyse → "analyse"
//   Version → "version"
//
// The `///` doc comment above each variant becomes the
// description shown in `--help` for that subcommand.
#[derive(Subcommand)]
pub enum Command {
    /// Analyze a file or directory
    Analyse {
        // `#[arg(help = "...")]` sets the help text for this
        // positional argument. Without it, positional args
        // inside subcommand variants don't show help text.
        #[arg(help = "Path to the file or directory to analyze")]
        path: String,
    },
    /// Show version information
    Version,
}

// Entry point for CLI parsing
// A thin wrapper. `Cli::parse()` is generated by the derive
// macro. It collects `env::args()`, validates them, and returns
// `Cli`. If the user passes `--help`, `--version`, or invalid
// arguments, clap prints the appropriate message and calls
// `process::exit()` internally — no error handling needed here.
pub fn parse_args() -> Cli {
    Cli::parse()
}
